///
/// MIT License
///
/// Copyright (c) 2020-present Cloudogu GmbH and Contributors
///
/// Permission is hereby granted, free of charge, to any person obtaining a copy
/// of this software and associated documentation files (the "Software"), to deal
/// in the Software without restriction, including without limitation the rights
/// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
/// copies of the Software, and to permit persons to whom the Software is
/// furnished to do so, subject to the following conditions:
///
/// The above copyright notice and this permission notice shall be included in all
/// copies or substantial portions of the Software.
///
/// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
/// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
/// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
/// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
/// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
/// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
/// SOFTWARE.
///

const languages = [
  "abap",
  "abc",
  "actionscript",
  "ada",
  "apache_conf",
  "apex",
  "applescript",
  "aql",
  "asciidoc",
  "asl",
  "assembly_x86",
  "autohotkey",
  "batchfile",
  "bro",
  "c9search",
  "c_cpp",
  "cirru",
  "clojure",
  "cobol",
  "coffee",
  "coldfusion",
  "crystal",
  "csharp",
  "csound_document",
  "csound_orchestra",
  "csound_score",
  "csp",
  "css",
  "curly",
  "d",
  "dart",
  "diff",
  "django",
  "dockerfile",
  "dot",
  "drools",
  "edifact",
  "eiffel",
  "ejs",
  "elixir",
  "elm",
  "erlang",
  "forth",
  "fortran",
  "fsharp",
  "fsl",
  "ftl",
  "gcode",
  "gherkin",
  "gitignore",
  "glsl",
  "gobstones",
  "golang",
  "graphqlschema",
  "groovy",
  "haml",
  "handlebars",
  "haskell",
  "haskell_cabal",
  "haxe",
  "hjson",
  "html",
  "html_elixir",
  "html_ruby",
  "ini",
  "io",
  "jack",
  "jade",
  "java",
  "javascript",
  "json",
  "jsoniq",
  "jsp",
  "jssm",
  "jsx",
  "julia",
  "kotlin",
  "latex",
  "less",
  "liquid",
  "lisp",
  "livescript",
  "logiql",
  "logtalk",
  "lsl",
  "lua",
  "luapage",
  "lucene",
  "makefile",
  "markdown",
  "mask",
  "matlab",
  "maze",
  "mel",
  "mixal",
  "mushcode",
  "mysql",
  "nginx",
  "nim",
  "nix",
  "nsis",
  "objectivec",
  "ocaml",
  "pascal",
  "perl",
  "perl6",
  "pgsql",
  "php",
  "php_laravel_blade",
  "pig",
  "plain_text",
  "powershell",
  "praat",
  "prolog",
  "properties",
  "protobuf",
  "puppet",
  "python",
  "r",
  "razor",
  "rdoc",
  "red",
  "redshift",
  "rhtml",
  "rst",
  "ruby",
  "rust",
  "sass",
  "scad",
  "scala",
  "scheme",
  "scss",
  "sh",
  "sjs",
  "slim",
  "smarty",
  "snippets",
  "soy_template",
  "space",
  "sparql",
  "sql",
  "sqlserver",
  "stylus",
  "svg",
  "swift",
  "tcl",
  "terraform",
  "tex",
  "text",
  "textile",
  "toml",
  "tsx",
  "turtle",
  "twig",
  "typescript",
  "vala",
  "vbscript",
  "velocity",
  "verilog",
  "vhdl",
  "visualforce",
  "wollok",
  "xml",
  "xquery",
  "yaml",
  "zeek"
];
export default languages;
